"""change embedding dim to 384

Revision ID: b72ebe7148e0
Revises: 4c8c23c3292c
Create Date: 2026-08-16 20:30:09.458172

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'b72ebe7148e0'
down_revision: Union[str, Sequence[str], None] = '4c8c23c3292c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE chunks ALTER COLUMN embedding TYPE vector(384)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE chunks ALTER COLUMN embedding TYPE vector(1536)")
    # ### end Alembic commands ###
